Task 10
pythoneyron/test_guru pull request #11
Opened 2021-06-11 18:31 UTC by pythoneyron

2021-06-11 19:31 UTC, BubuntuClu requested changes

2021-06-11 19:31 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def find_user
этот метод не нужен больше совсем. используй `current_user` метод, где надо получить пользователя

2021-06-11 19:31 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +  included do
эт что? зачем это тут? валидация должна быть в моделе

2021-06-11 19:31 UTC, BubuntuClu commented on app/models/user.rb
> +  before_validation :before_validation_correct_email, on: :create
есть стандартный механизм валидации почты, стоит его использовать

2021-06-11 19:31 UTC, BubuntuClu commented on config/routes.rb
> +  get 'sessions/new'
этот и роут ниже не нужны. они дублируют роуты с 8 строки

2021-06-11 19:31 UTC, BubuntuClu commented on db/migrate/20210609074141_add_password_digest_to_users.rb
> +    add_column :users, :email, :string
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный индекс надо

2021-06-12 02:50 UTC, pythoneyron commented on app/controllers/users_controller.rb
> +  included do
По ошибке не туда перенес. Исправил)

2021-06-13 06:52 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :current_user, only: %i[start]
не так, у тебя этот метод описан в application_controller. его не надо в колбэк записывать. там где тебе нужен пользователь там и пишешь `current_user`.

тебе в методе `start` надо заменить `@user` на этот метод. сейчас у тебя запуск теста не будет работать

2021-06-13 06:52 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add('Answers on question too many') if question.answers.count >= ANSWERS_LIMIT_ON_QUESTION if question
у тебя по идеи не может быть ответа без вопросов, тут проверка не очень нужна

2021-06-13 06:52 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
`validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }`

2021-06-13 06:52 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :password, presence: true, if: Proc.new { |u| u.password_digest.blank? }
тоже в одну строку

2021-06-13 06:53 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:redirect_to]
`redirect_to cookies[:redirect_to] || tests_path`

2021-06-13 06:54 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:redirect_to] ? session[:redirect_to] : tests_path
`redirect_to session[:redirect_to] || tests_path`

2021-06-13 19:43 UTC, BubuntuClu approved these changes

2021-06-13 19:43 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :find_user, only: %i[start]
это удали. зачем теперь тебе этот метод?

2021-06-13 19:43 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  def find_user
это удали. зачем теперь тебе этот метод?

2021-06-13 19:56 UTC, merged