Task 17
pythoneyron/test_guru pull request #18
Opened 2021-07-06 17:50 UTC by pythoneyron

2021-07-06 18:22 UTC, BubuntuClu commented on app/mailers/tests_mailer.rb
> +    mail to: User.find_by(type: 'Admin').email
`Admin.all.map(&:email)`

2021-07-07 06:46 UTC, BubuntuClu requested changes

2021-07-07 06:46 UTC, BubuntuClu commented on db/migrate/20210707040220_delete_relations_test_passage.rb
> +class DeleteRelationsTestPassage < ActiveRecord::Migration[6.1]
это не выход. надо найти другое решение, без пересоздания внешнего ключа.

посмотри опции у ассоциаций, у них есть вариант `dependent`

2021-07-07 06:46 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :authenticate_user!, except: :action_here
чет не понял что за `except: :action_here`? можешь пояснить?

2021-07-07 08:36 UTC, prog-supdex commented on app/mailers/tests_mailer.rb
> +    mail to: User.find_by(type: 'Admin').email
```
Admin.pluck(:email)
```

2021-07-07 11:47 UTC, merged