create migrations
pythoneyron/test_guru pull request #2
Opened 2021-05-20 06:22 UTC by pythoneyron

2021-05-20 07:05 UTC, BubuntuClu requested changes

2021-05-20 07:05 UTC, BubuntuClu commented on db/migrate/20210520053253_create_tests.rb
> +      t.integer :level
нужно добавить внешний ключ и индекс на поле внешнего ключа к таблице категорий.
посмотри команду `t.references`

2021-05-20 07:05 UTC, BubuntuClu commented on db/migrate/20210520053431_create_questions.rb
> +      t.string :body
нужно добавить внешний ключ и индекс на поле внешнего ключа к таблице тестов.

2021-05-20 07:05 UTC, BubuntuClu commented on db/migrate/20210520055540_create_answers.rb
> +
нужно добавить внешний ключ и индекс на поле внешнего ключа к таблице вопросов.

2021-05-20 07:05 UTC, BubuntuClu commented on db/migrate/20210520055540_create_answers.rb
> +      t.string :correct
это логично сделать булевым полем, так как ответ может быть либо правильны, либо нет

2021-05-20 19:16 UTC, BubuntuClu approved these changes

2021-05-20 19:16 UTC, BubuntuClu commented on db/migrate/20210520061505_add_tables_value_default.rb
> +    change_column_default(:answers, :correct, nil)
дефолтное значение false

2021-05-20 19:16 UTC, BubuntuClu commented on db/migrate/20210520053253_create_tests.rb
> +      t.references :categories, foreign_key: true
связь должна быть в единственном числе
` t.references :category, foreign_key: true`

в файле schema.rb ты можешь посмотреть что получилось
```
create_table "tests", force: :cascade do |t|    
t.string "title", null: false    
t.integer "level", default: 0    
t.integer "categories_id"    
t.datetime "created_at", precision: 6, null: false    
t.datetime "updated_at", precision: 6, null: false    
t.index ["categories_id"], name: "index_tests_on_categories_id"  
end
```

видишь, поле получилось `categories_id`, а это неправильно

2021-05-20 19:16 UTC, BubuntuClu commented on db/migrate/20210520053253_create_tests.rb
> +      t.references :categories, foreign_key: true
в других связях тоже надо поправить

2021-05-21 06:05 UTC, pythoneyron commented on db/migrate/20210520061505_add_tables_value_default.rb
> +    change_column_default(:answers, :correct, nil)
Я все же считаю, что сохранять по умолчанию как не правильный ответ не совсем верное решение. Я исправил на false.

2021-05-21 06:06 UTC, pythoneyron commented on db/migrate/20210520053253_create_tests.rb
> +      t.references :categories, foreign_key: true
Понял, исправляю.

2021-05-21 06:18 UTC, merged

2021-05-21 06:55 UTC, BubuntuClu commented on db/migrate/20210520061505_add_tables_value_default.rb
> +    change_column_default(:answers, :correct, nil)
почему? у тебя возможно всего 2 варианта. обычно тест предполагает 1 правильный ответ, значит все остальные это неправилные. зачем насильно заставлять проставль "неправильный"?

не может быть `correct` никакой/nil/null, это не имеет смысла