Task 5
pythoneyron/test_guru pull request #4
Opened 2021-05-25 06:26 UTC by pythoneyron

2021-05-25 07:22 UTC, BubuntuClu commented on app/models/test.rb
> +    # joins('INNER JOIN categories ON tests.category_id = categories.id')
комменты удаляй, не надо тянуть их в репу

2021-05-25 08:35 UTC, pythoneyron commented on app/models/test.rb
> +    # joins('INNER JOIN categories ON tests.category_id = categories.id')
Исправил

2021-05-25 08:53 UTC, BubuntuClu requested changes

2021-05-25 08:53 UTC, BubuntuClu commented on db/migrate/20210520053524_create_users.rb
> +      t.boolean :is_author, default: false
этого не достаточно. это тебе никак не говорит о том какой тест создал этот пользователь. и так же от теста ты никак не узнаешь кто его автор.
тут должна быть связь с тестами. в моделях пользователя/тестов надо еще добавить ассоциации для получения созданых тестов/пользователя

2021-05-25 19:26 UTC, BubuntuClu requested changes

2021-05-25 19:26 UTC, BubuntuClu commented on db/migrate/20210520053524_create_users.rb
> +      t.boolean :is_author, default: false
эту строку надо удалить. забыл в тот раз написать, что нельзя править миграции, которые уже слиты в мастер

2021-05-25 19:26 UTC, BubuntuClu commented on db/migrate/20210525120423_add_author_id_column_to_tests.rb
> +    add_column :tests, :author_id, :integer
есть команда `add_references`, стоит ее использовать

2021-05-25 19:26 UTC, BubuntuClu commented on db/migrate/20210520053524_create_users.rb
> +      t.boolean :is_author, default: false
а про
>Между Тестом и автором (Пользователем), который его создал.
забыл? или не запушил? выше об этом тоже писал

2021-05-26 07:13 UTC, BubuntuClu approved these changes

2021-05-26 07:13 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
тут тоже надо указать внешний ключ, так как он отличается от `user_id`

2021-05-26 07:13 UTC, BubuntuClu commented on db/migrate/20210526041849_add_is_author_to_users.rb
> +class AddIsAuthorToUsers < ActiveRecord::Migration[6.1]
эта миграция лишняя, она не нужна.

2021-05-26 10:45 UTC, merged

2021-05-26 11:02 UTC, BubuntuClu commented on db/migrate/20210526041849_add_is_author_to_users.rb
> +class AddIsAuthorToUsers < ActiveRecord::Migration[6.1]
этот файл целиком не нужен. откати миграцию и удали файл